# Generated by Django 5.1.5 on 2025-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='posts',
            field=models.ManyToManyField(null=True, related_name='catalogs', to='posts.post'),
        ),
    ]
