# Generated by Django 5.1.5 on 2025-01-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalog_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='posts',
        ),
    ]
